#!/bin/sh
### BEGIN INIT INFO
# Provides:          domiq-base
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Start/stop domiq-base proxy
### END INIT INFO

DAEMON=/usr/bin/python
ARGS="/usr/local/sbin/domiq-base -d <ip-or-host> -c 3600"
PIDFILE=/var/run/domiq-base.pid

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user domiq-base --group domiq-base \
        -b --make-pidfile \
        --chuid domiq-base \
        --exec $DAEMON -- $ARGS
    ;;
  stop)
    echo "Stopping server"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  *)
    echo "Usage: /etc/init.d/domiq-base {start|stop}"
    exit 1
    ;;
esac

exit 0

